---
- name: Seeding Custom Playbooks
  hosts: localhost
  gather_facts: false
  environment:
    CONTROLLER_USERNAME: "{{ lookup('env', 'CONTROLLER_USERNAME') }}"
    CONTROLLER_PASSWORD: "{{ lookup('env', 'CONTROLLER_PASSWORD') }}"
    CONTROLLER_HOST: "{{ lookup('env', 'CONTROLLER_HOST') }}"
    CONTROLLER_VERIFY_SSL: false
  tasks:

    - name: Create temp dir
      ansible.builtin.tempfile:
        state: directory
        suffix: build
      register: tmp_dir

    - name: Get Custom Playbooks content
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ tmp_dir.path}}/{{ seed_custom_cac_url.split("/")[-1] }}'

    # TODO(spredzy): Temporary hack until include_vars is solved
    #
    - name: Create same dir on EE
      ansible.builtin.file:
        path: "{{ tmp_dir.path }}"
        state: directory
      delegate_to: localhost

    - name: Get Custom Playbooks content on EE
      ansible.builtin.git:
        repo: '{{ seed_custom_cac_url }}'
        dest: '{{ tmp_dir.path}}/{{ seed_custom_cac_url.split("/")[-1] }}'
      delegate_to: localhost
    # END-OF-HACK

    - name: Get all experiences in collection
      ansible.builtin.find:
        paths: '{{ tmp_dir.path }}/{{ seed_custom_cac_url.split("/")[-1] }}'
        patterns: setup.yml
        recurse: true
      register: experiences

    - name: Load experiences
      ansible.builtin.include_tasks: load_experience.yml
      loop: '{{ experiences.files }}'
      loop_control:
        loop_var: experience
